### ISSUE TITLE
add cross-correlation forest_1 forest_2

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#100]
I would like to look at adding the cross-correlation forest_1 forest_2.
I think I should create two new files one do_xcf_forest.py and one xcf_forest.py.
What do you think @ngbusca ?

**Comment by ngbusca** [comment]
I thought @vserret was working on this since it's directly related to lyb x lya...

**Comment by londumas** [comment]
I didn't know, @vserret , can you confirm ?

**Comment by vserret** [comment]
I am working on it with my code in cpp, but I can do it in python

**Comment by londumas** [comment]
@vserret it would be super usefull in Python. You would just have to adapt the code for the auto-correlation

**Comment by vserret** [comment]
I try to do it before the end of the next week

**Comment by londumas** [comment]
@vserret is it done in the latest comits ?
Can we close it ?

**Comment by vserret** [comment]
It is done. 
There is an opton in 'do_cf.py', if you want to compute a forest cross-correlation you have to add a (-lambda-abs2)second directory with the data ( --in-dir2) and (if you want to ), an absorption wavelength (--lambda-abs2).
