### ISSUE TITLE
small bug in parser for do_xcf.py

### ISSUE THREAD

**Issue by jmarclegoff** [igmhub/pyLyA#103]
There is a mismatch ("-" vs "_" ) between
line 86
    parser.add_argument('--no-remove-mean-lambda-obs', action="store_true", required=False,
and line 142
    if not args.no_remove_mean_lambda_obs:

**Comment by londumas** [comment]
The mismatch ("-" vs "_" ) is normal. That is how argparse works.
Do you see some problems because of this mismatch ?

**Comment by jmarclegoff** [comment]
No problem indeed.
Sorry
