### ISSUE TITLE
change resources to etc

### ISSUE THREAD

**Issue by ngbusca** [igmhub/pyLyA#105]
@londumas any objections to changing the name of the "resources" directory to the more standard and shorter "etc"?

**Comment by londumas** [comment]
no, go ahead

**Comment by londumas** [comment]
By the way, I prefer that repositories start with an upper case and files with a lower.
But if you don't want to change, no problem. It isn't important.

**Comment by ngbusca** [comment]
do you mean like PyLyA instead of pyLyA, etc?

**Comment by londumas** [comment]
yes and like "Bin" instead of "bin"

**Comment by ngbusca** [comment]
Oh, so not the repositories, but the directories. This is really really really not standard, take a look at any other directory in any other repository (and I'd argue not even aesthetic, but that's not very objective).

**Comment by londumas** [comment]
Anyway, this is not important, let's forget about that.
It will not have an impact on the position of the BAO peak :)

**Comment by ngbusca** [comment]
fixed
