### ISSUE TITLE
mean continuum has fixed nb_bins

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#14]
in py/pylya/prep_del.py,
the mc() (and other histos) has a constant number of bins,
this produces problems when looking at a wide range in lambda_rf (for example the overall quasar spectrum).

We could find a way to get this controlled by the user.

**Comment by londumas** [comment]
The physics of lines is naturally described in a grid constant in lambda_RF.
The grid could be then constant in delta_RF, with a step given by the user
or something like every 1A.

**Comment by ngbusca** [comment]
I prefer the loglam grid because it's the spacing is same in rest and lab frame. We could determine the number of bins from lambda-rest-min, lambda-rest-max and the bin size (given by rebin * 1e-4)

**Comment by londumas** [comment]
ok, I leave you do that.

**Comment by londumas** [comment]
fixed in fix_issue_14
