### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mubecks** [igmhub/pyLyA#143]
Hello again!

I updated files of pyLyA using git clone, then I re-run do_deltas.py but here is some error.
I used same commands, mode, data files and catalog as before I submitted error issue.

determining nside
nside = 8 -- mean #obj per pixel = 927
0 read from pix 18, 0 242 in 0.463008880615 secs per spectrum
0 read from pix 29, 1 242 in 0.196218490601 secs per spectrum
0 read from pix 30, 2 242 in 4.84800338745 secs per spectrum
0 read from pix 31, 3 242 in 11.8579864502 secs per spectrum
0 read from pix 32, 4 242 in 14.7941112518 secs per spectrum
0 read from pix 33, 5 242 in 7.31897354126 secs per spectrum
0 read from pix 34, 6 242 in 0.710010528564 secs per spectrum
Traceback (most recent call last):
  File "bin/do_deltas.py", line 160, in <module>
    zmin=args.zqso_min,zmax=args.zqso_max,nspec=args.nspec,log=log,keep_bal=args.keep_bal,bi_max = args.bi_max)
  File "build/bdist.linux-x86_64/egg/pylya/io.py", line 167, in read_data
    
  File "build/bdist.linux-x86_64/egg/pylya/io.py", line 201, in read_from_spec
    
TypeError: __init__() takes exactly 12 arguments (11 given)

**Comment by ngbusca** [comment]
did you rerun python setup.py install?

**Comment by mubecks** [comment]
Yes, after I reran python setup.py install --user, I did do_deltas.py

**Comment by ngbusca** [comment]
git clone doesn't update the code, you need to do 

```
git pull
```

**Comment by mubecks** [comment]
Ah, I didn't know that.
But before git clone the pyLyA, first I deleted before version of pyLyA (actually not delete completely but in trashcan folder).
Can it be make any error like I have?

**Comment by mubecks** [comment]
Just now, I recovered before version and did

git pull, rerun setup.py install

but still have same TypeError: init() takes exactly 12 arguments (11 given)

**Comment by ngbusca** [comment]
can you rerun 

```
git pull
```

then 

```
python setup.py install
```
and try again?

**Comment by mubecks** [comment]
Still doesn't work...

**Comment by ngbusca** [comment]
can you erase your current version of the code and reinstall from scratch?

**Comment by mubecks** [comment]
I tried from the beginning but not work.

**Comment by ngbusca** [comment]
do you still get the same error?

**Comment by mubecks** [comment]
Yes still get the same error.

**Comment by ngbusca** [comment]
I don't think you have really cleaned your system from the old installation. Please follow the instructions from here: https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

Then redo 
```
python setup.py install --user
```

**Comment by mubecks** [comment]
It is working now.
I think you are right. It didn't clean the old installation so your latest fixing didn't apply.
