### ISSUE TITLE
degeneraci between mean continuum and stack

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#15]
There is currently a degeneracy between the mean continuum (flux vs. l_RF) and the stack (flux vs l_obs).
This degeneracy could be broken by constraining the continuum to be 1 at some wavelength,
for example l_rf = 1280

This changes nothing to the calculation of delta but allows the different stack and continuum to be compared between forests.

**Comment by ngbusca** [comment]
I disagree, the mean continuum is normalized to 1, which breaks the degeneracy.

**Comment by londumas** [comment]
Yes, it breaks the degeneracy.
But then if one look at the continuum in one range and the other one in an other range,
then we can't compare them. Even if one range is inside the other.

**Comment by londumas** [comment]
With this definition then the stack is a fluctuation around 1 (like figure 4 of the auto-correlation paper) and the mean-continuum as a fixed value in 1280, always the same one.

How does your stack and your mean-continuum look like ?
