### ISSUE TITLE
continuum fitting fails with complex numbers

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#17]
Sometime for some low S/N spectrum I get:

/home/gpfs/manip/mnt0607/bao/hdumasde/Program/Igm_hub/pyLyA/py/pylya/data.py:145: ComplexWarning: Casting complex values to real discards the imaginary part
  mig.migrad()

To investigate, but seems to be linked to the quasar continuum going negative, zero or from negative to positive. 

I get that with:
/home/gpfs/manip/mnt0607/bao/hdumasde/Program/Igm_hub/pyLyA/bin/do_deltas.py --in-dir /home/gpfs/manip/mnt0607/bao/Spectra/SpectraV5_10_0 --drq /home/gpfs/manip/mnt0607/bao/Spectra/DR14Q_v1_1.fits --out-dir /home/gpfs/manip/mnt0607/bao/hdumasde/Code/Igm_Hub/Test_pyLya/ --rebin 1 --mode spec --zqso-min 6.0 --zqso-max 10.0 --lambda-min 3600.0 --lambda-max 7235.0 --lambda-rest-min 0.001 --lambda-rest-max 10000.0

**Comment by londumas** [comment]
Seems to be linked also to unmasked skylines

**Comment by ngbusca** [comment]
You are pushing the code into realms were it wasn't built to work... I'm not sure I wan't to fix this

**Comment by andreufont** [comment]
Now that you are looking at it, Hélion, it would be quite interesting to
look at what fraction of spectra do not get a valid continuum from the
code, as a function of quasar redshift and magnitude (r).

Andreu

**Comment by londumas** [comment]
I kind of disagree Nicolas,
We want the code to perform everywhere, not only in the Lyman-alpha forest region.
So we should track such fails, see the reason why and remove them from our forest list.

Maybe we should add a self.fit_is_correct bool in the forest to see if the fit is good, at least test the "is_valid" value of iminiut.

**Comment by ngbusca** [comment]
Sorry, but these flags:

--lambda-rest-min 0.001 --lambda-rest-max 10000.0

don't make sense.

@andreufont the continuum fit doesn't fail on any spectrum.

**Comment by andreufont** [comment]
Wow! That's impressive. I thought you had a minimum SNR for which you were
able to get a good continuum fit. Are there no quasars in DR12Q that are
pathological, or that have all pixels in the forest masked?

Andreu

**Comment by londumas** [comment]
@ngbusca 
I don't say that the continuum only fails when taking
--lambda-rest-min 0.001 --lambda-rest-max 10000.0
I just put the command to keep track,
what quasars does that is yet to understand and find.

The only things I know now is that it happens for some cases.

**Comment by ngbusca** [comment]
@andreufont I preselect spectra with 50 or more unmasked pixels

**Comment by ngbusca** [comment]
@londumas then please give an example of more standard choices that result in the same problem

**Comment by londumas** [comment]
This happens with "forest.var_lss" giving negative numbers through interpolation.
Then the code takes sp.log(we), where we=iv/(iv*var_lss*m**2+1).
Apparently the log value of a negative number is a complex.

This happens when the "var_lss" is not well measured or extrapolated way out if its range.

For example at the blue of the lyman-alpha forest, I don't know if there are other cases, maybe we can neglect this effect.

python /home/gpfs/manip/mnt0607/bao/hdumasde/Program/Igm_hub/pyLyA/bin/do_deltas.py --in-dir /home/gpfs/manip/mnt0607/bao/Spectra/SpectraV5_10_0 --drq /home/gpfs/manip/mnt0607/bao/Spectra/DR14Q_v1_1.fits --out-dir /home/gpfs/manip/mnt0607/bao/hdumasde/Code/Igm_Hub/Test_pyLya/ --rebin 1 --mode spec --zqso-min 5.0 --zqso-max 6.0 --lambda-min 3600.0 --lambda-max 7235.0 --lambda-rest-min 100.0 --lambda-rest-max 800.0

**Comment by londumas** [comment]
An easiy fix is to add
`
var_lss[(var_lss<0.)] = 0.
`
after
`
var_lss = forest.var_lss(self.ll)
`

**Comment by ngbusca** [comment]
can I close this issue?

**Comment by londumas** [comment]
won't fix since seems to append with unrealistic configuration
