### ISSUE TITLE
Correct for flux calibration

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#18]
The pipeline has some mistakes due to calibration stars and skylines
(see figure 4 of auto-correlation paper: Bautista et al.).
A nice way to correct for this is to estimate it in the red side of the forest.

Do we want to have the possibility to correct the flux of forests by this effect.
Maybe by giving an asci or .fits file with:
lambda_obs correction err_correction
and correcting the flux and the ivar of the data

**Comment by ngbusca** [comment]
This functionality is in the current baseline analysis but hasn't yet been ported to pyLyA (it's in the to-do list)

**Comment by londumas** [comment]
ok, how do you see such a correction ?
Maybe feeding the code with another "iter.fits.gz" file.
This make more sense.

**Comment by londumas** [comment]
It would take the field loglam and stack from a given file and correct with it.

Here what it looks like from the CIV forest
![correction_flux](https://cloud.githubusercontent.com/assets/3166436/22416974/f5e2c20a-e6d1-11e6-9d6b-3100cb896007.png)

**Comment by ngbusca** [comment]
The correction should be read from the iter.fits.gz file that the user previously generated by running do_deltas on civ with the same choice of lambda-obs-min and lambda-obs-max, so as to have the same binning.

Then, as fluxes are read from the files, they should be divided by the correction. Note that this only corrects for multiplicative residuals.

**Comment by londumas** [comment]
Agreed,
We could add a method to "forest", similar to "cont_fit".
i.e. using a interp1d to correct the flux and the invers variance (fl and iv) if the option is there.

What do you say ?

**Comment by ngbusca** [comment]
In the __init__ of the class forest I'd add a keyword with the correction vector (None by default). If this vector is not None, then divide the flux by it (and multiply iv by this squared).

No interpolation, assume that the wavelength grids are the same (interpolating still leaves residuals).

**Comment by londumas** [comment]
ok.
Is the grid for the stack the same as for the data ?
If yes then no problem, we just have to do a test on the  "iter.fits.gz" of calibration to see if it is on the same grid, with the same range of lambda_obs.

**Comment by londumas** [comment]
We can also just add a correct_flux(self,correction) method to the class forest.
Where correction is the vector.

What do you prefer ?

**Comment by londumas** [comment]
fixed in fix_issue_18
