### ISSUE TITLE
bug in reading the data

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#4]
I tested with a small number of spectra.

I get:

`
hdumasde@hdumasde:~/Documents/Documents/Thèse/Code/Igm_hub/pyLyA$ python bin/do_deltas.py --in-dir /home/hdumasde/Documents/Documents/Thèse/Data/SpectraV5_10_0/ --drq ../../../Data/DR14Q_v1_1.fits --out-dir ../../../Data/Deltas --mode spec --zqso-min -10.0 --zqso-max 10.0

BAL_FLAG_VI not found, ignoring BAL

446140

determining nside

nside = 16 -- mean #obj per pixel = 507

0 read from pix 1829, 878 879

iteration:  0

Traceback (most recent call last):
  File "bin/do_deltas.py", line 144, in <module>
    data_fit_cont = pool.map(cont_fit, data.values())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: could not convert string to float: extrapolate
`

**Comment by ngbusca** [comment]
scipy version 0.17.0 or higher is required
