### ISSUE TITLE
remove empty bin in interp1d

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#41]
At some place in the code, there are definitions of interpolation function.
empty bins should be removed before definitions.

In:
   - do_deltas.py
   - do_dmat.py
   - do_wick
   - do_xdmat

**Comment by londumas** [comment]
for do_wick, we need to put the number of bins or/and the sum of weights when saving
do_cf1d.py, is that good for you ?

**Comment by ngbusca** [comment]
let's put both...

**Comment by londumas** [comment]
fixed in fix_issue_41
