### ISSUE TITLE
Add mask for lines in the DLA rest frame

### ISSUE THREAD

**Issue by ngbusca** [igmhub/pyLyA#46]
We might want to mask dla metal lines, this requires a mask in the DLA rest.

**Comment by londumas** [comment]
Or we could correct for them the same way we do for DLA,
i.e. with a correction to the flux.

**Comment by londumas** [comment]
It might be also important to do it not only for metals but also for Lyb

**Comment by londumas** [comment]
Figure 7 and 8 of Mas-Ribas et al. could be useful.
https://arxiv.org/abs/1610.02711

**Comment by ngbusca** [comment]
we masked dla metals and lybeta in Delubac et al. but not for the later analyses. It didn't make a difference but it's cleaner to do it.

**Comment by londumas** [comment]
But do we want to mask Lyb and metals or correct them the same way we do for the DLA(Lya) ?
I would tend to correct them.

**Comment by londumas** [comment]
In my cross analysis I also only take into account the DLA(Lya) line.
I have tested with corrections of metal lines, and although it is nicer, it gives no much differences.
Maybe only in the strength of the metals in the cross and auto correlation.

I tried something like that, where the strength of the metals where from the stack of DLA.
In practice it should ba a function of the strenth of the DLA.
![capture du 2017-02-16 10-57-07](https://cloud.githubusercontent.com/assets/3166436/23016408/ad8a8976-f436-11e6-808a-e0f7e8c145bb.png)

**Comment by londumas** [comment]
Where each metal is given as a gaussian (eq. 9 of Mas-Ribas et al.) of constant "a".
The strength should be given by the figure 11.

I don't know if we want to go that far,
but it is something I tried to see the effect some time ago.

**Comment by londumas** [comment]
Parameters  pyLyA/py/pylya/dla.py are hard codded.
Where does these parameters come from ?

**Comment by ngbusca** [comment]
From Pasquier

**Comment by londumas** [comment]
but a paper or himself ?

**Comment by ngbusca** [comment]
I use the exact same parameters that define his dla profile. He gave me his code that I translated into python, I took them from there

**Comment by londumas** [comment]
Ok, I see.
That is why for example "c = 3e8".
Because then we have the result of the best fit.
OK.

**Comment by ngbusca** [comment]
Yes, that's a good idea

**Comment by londumas** [comment]
fixed in fix_issue_46
