### ISSUE TITLE
and_mask cut is hard coded and fixed to 0

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#47]
In  pyLyA/py/pylya/data.py,
the code cuts all pixels with "AND_MASK!=0",
this can change from analysis to analysis.
It could be put as an argument in the parser of  pyLyA/bin/do_deltas.py.

In the current cross analysis, I remove only AND_MASK>2^16.

**Comment by londumas** [comment]
Looking on the first 10,000 quasar spectra, we have:

The first plot gives the distribution of LAMBDA_OBS for all the pixels with a AND_MASK not zero.
![distibution_lambdaobs_notzeroandmaskpixel](https://cloud.githubusercontent.com/assets/3166436/22967344/64e82fd2-f366-11e6-8bc4-daa3156271f5.png)

The second plot gives the percent of pixels with a given AND_MASK value,
the point of abscisse 0, is the AND_MASK=0
![percent_of_pixel_with_some_value_of_andmask](https://cloud.githubusercontent.com/assets/3166436/22967345/64ea7a30-f366-11e6-9d8a-d7e0b553b353.png)

**Comment by ngbusca** [comment]
A mask says that something was wrong in the extraction. It's dangerous to leave crap in the analysis.

**Comment by londumas** [comment]
It is a good point,
and any way the second figure shows that we loose only a few.

In the SDSS wiki, they say, the folowing.
But we don't see any "AND_MASK=2^24" any way

> Mask Bits in Coadd (BOSS)
>
>In the SPPIXMASK associated with each spectrum, mask bit 24 (NODATA) should be ignored in the >AND_MASK of BOSS coadded spectra ( spPlate and spec). That is, a good pixel is one that satisfies the >conditions:
>
>good = (AND_MASK=0 or AND_MASK=2^24) and ivar > 0
>
>The NODATA bit is being incorrectly set in these cases near the overlap of the dichroic between the two >spectra. This error will be fixed in future reductions.

https://www.sdss3.org/dr9/algorithms/bitmask_sppixmask.php

**Comment by londumas** [comment]
To keep track,
this SDSS page describe the AND_MASK

https://www.sdss3.org/dr9/algorithms/bitmask_sppixmask.php

**Comment by andreufont** [comment]
Helion, your plot shows a peak on and_mask = 2^24, isn't it?
Andreu

**Comment by londumas** [comment]
@andreufont ,
Sorry there was a mistake in the last version of the plot.
The point is at "and_mask = 2^23" (i.e. BRIGHTSKY).
That is why a lot of these pixels have lambda_obs > 7000 A

**Comment by andreufont** [comment]
It makes sense. Thanks!
Andreu
