### ISSUE TITLE
indentation is hard

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#5]
This is an open question:

The indentation you make seems to be with 4-spaces.

It makes a painfull work when multiple indentation are to be used.

Why not using the "indent key" ? There is then no counting.

**Comment by londumas** [comment]
Currently the indentation is a mixe of spaces and indent.
This makes strange to see.

See picture bellow with a mix of different indentation.
![indentation](https://cloud.githubusercontent.com/assets/3166436/22206819/04fc0f9e-e17d-11e6-9185-5e5343f2a751.png)

**Comment by londumas** [comment]
On another editor, it makes sense.
![indentation_2](https://cloud.githubusercontent.com/assets/3166436/22206935/5dbad070-e17d-11e6-8717-30f700b24706.png)

**Comment by londumas** [comment]
It isn't very nice to have different behaviour with different editor.

**Comment by andreufont** [comment]
Helion, it is important to use always either one or the other, you don't want to mix tabs with spaces. Python style guide recommends to use 4 spaces for indentation
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
and what I do is setup my editor to print 4 spaces when I hit the tab key.

**Comment by londumas** [comment]
Yes I agree that we should use one or the other, not both.

This is the current state of the code.

**Comment by ngbusca** [comment]
Many things in life are hard...

**Comment by ngbusca** [comment]
In the head I've replaced all tabs by 4 spaces... It should be ok now...
