### ISSUE TITLE
definition of eta is inverse of papers

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#51]
The definition of "eta" in the code is the inverse of the definition in the papers

"eta" is given as a function of z in https://arxiv.org/pdf/1211.2616.pdf, figure 6.

In the code it gives the blue line of the following plot
![capture du 2017-02-17 11-02-34](https://cloud.githubusercontent.com/assets/3166436/23061094/c46dd114-f500-11e6-8c3a-cd35b977fa1c.png)

**Comment by ngbusca** [comment]
yes, it's the inverse

**Comment by londumas** [comment]
fixed in fix_issue_51
