### ISSUE TITLE
range limit of sigma 2 LSS is too low

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#53]
The range "limit_vlss=(0.0,0.3)" is too low in the Lya forest and the Lyb forest.

![capture du 2017-02-18 10-00-10](https://cloud.githubusercontent.com/assets/3166436/23091946/3281232a-f5c1-11e6-8916-3f2fd216d637.png)

**Comment by londumas** [comment]
would a new limit of (0.0,1.) work for you ?

**Comment by ngbusca** [comment]
That's ok, although I'd be very careful with using data from the red spectrograph, since there are many many skylines in the red.

**Comment by londumas** [comment]
ok, I will do the merge request

**Comment by londumas** [comment]
corrected and tested in fix_issue_53
