### ISSUE TITLE
Spead of light value

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#54]
In constants, cosmo:  https://github.com/igmhub/pyLyA/blob/master/py/pylya/constants.py

The value of c is 299792.4583
Where does the last "3" comes from ?

It isn't in the definition I have
https://fr.wikipedia.org/wiki/Vitesse_de_la_lumi%C3%A8re

Anyway, it doesn't change much

**Comment by ngbusca** [comment]
No clue, I just fixed it in master
