### ISSUE TITLE
D_A vs. D_M

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#55]
In https://github.com/igmhub/pyLyA/blob/master/py/pylya/constants.py,

for Ok=0, the code gives
self.da = interpolate.interp1d(z,chi)
which seems to be "dm" actually.

**Comment by ngbusca** [comment]
Yes, da is the "comoving" angular diameter distance, also for Ok != 0. I don't think the notation "dm" is standard. In any case, I've added a comment in the code to make it clear.
