### ISSUE TITLE
if ok!=0, self.da no longer a function

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#56]
ig Ok<0 or Ok>0, delf.da is a scipy array.

We should have:
`

        if 0k==0.:

            self.da = chi

        elif Ok<0:

            self.da = sp.sin(H0*sp.sqrt(-Ok)/c*chi)/(H0*sp.sqrt(-Ok)/c)

        elif Ok>0:

             self.da = sp.sinh(H0*sp.sqrt(Ok)/c*chi)/(H0*sp.sqrt(Ok)/c)

        self.da = interpolate.interp1d(z,self.da)
`

**Comment by ngbusca** [comment]
Indeed. It should be now fixed in master, can you take a look?

**Comment by londumas** [comment]
fixed.
