### ISSUE TITLE
devide by zero in do_xdmat.py

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#71]
RuntimeWarning: invalid value encountered in divide
  dm/=wdm

**Comment by londumas** [comment]
I can't correct that the simple way (i.e. dm[wdm>0.] /= wdm[wdm>0.]), I get
ValueError: operands could not be broadcast together with shapes (4319,5000) (4319,) (4319,5000)
dm is a 5000*5000 2D scipy array and wdm is a 5000 1D scipy array

I don't understand what is happening. @ngbusca, do you have an idea ?

**Comment by ngbusca** [comment]
The dm[wdm>0] changes the sape of the arrays in a way that they can't be broadcasted. You have to do w = wdm>0, dm[:,w]=d[:,w]/wdm[w]

**Comment by londumas** [comment]
thanks for the answer.
fixed in fix_issue_71
