### ISSUE TITLE
io.py doesn't work with new pix format

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#77]
The new pix files are different:
nside=8 and 

  file: /home/gpfs/manip/mnt0607/bao/Spectra/Spectra_from_forest_Fusion/pixs/pix_30.fits
  extension: 0
  type: IMAGE_HDU
  extname: THING_ID_MAP
  image info:
    data type: i4
    dims: [425]

  file: /home/gpfs/manip/mnt0607/bao/Spectra/Spectra_from_forest_Fusion/pixs/pix_30.fits
  extension: 1
  type: IMAGE_HDU
  extname: LOGLAM_MAP
  image info:
    data type: f8
    dims: [4751]

  file: /home/gpfs/manip/mnt0607/bao/Spectra/Spectra_from_forest_Fusion/pixs/pix_30.fits
  extension: 2
  type: IMAGE_HDU
  extname: FLUX
  image info:
    data type: f4
    dims: [4751,425]

  file: /home/gpfs/manip/mnt0607/bao/Spectra/Spectra_from_forest_Fusion/pixs/pix_30.fits
  extension: 3
  type: IMAGE_HDU
  extname: IVAR
  image info:
    data type: f4
    dims: [4751,425]

we should adapt to be able to read these new files

**Comment by ngbusca** [comment]
@slosar is working on this

**Comment by londumas** [comment]
- @slosar how can all the spectrum have the same loglam_map ? This is not the case in spec files.
Did you rebin ?
   - @ngbusca do you want to kee the logic for the previous pix version ?

**Comment by ngbusca** [comment]
Yes, there's a rebinning to a common lambda grid. What do you mean the logic?

**Comment by londumas** [comment]
I mean, do you want the code to work for the previous version of pixels ?

**Comment by ngbusca** [comment]
No, I don't think that's necessary.

**Comment by londumas** [comment]
fixed in fix_issue_77

**Comment by slosar** [comment]
I've looked at this, looks good. In fact, I think for the time being, it is pretty efficient so having a full reading library inside ffusion is not a priority. But getting coadds is...
Who is londumas, Hélion? :)

**Comment by slosar** [comment]
In fact, quickly reopening this. NSIDE is stored in the header of master file, so you should read it from there -- should be one line fixer.

**Comment by londumas** [comment]
indeed, londumas is Hélion.
I will do this fix

**Comment by londumas** [comment]
@slosar is it ok if the code assumes that the master.fits file is in the same folder as the pixs file ?
It would be easier to code and simpler to structure.

**Comment by londumas** [comment]
if you don't like it we would have to add a command line giving the path to the master file, which doesn't seem necessary.

**Comment by slosar** [comment]
Actually, that is a good point. We can go with master files the same dir as it is not that many files.

**Comment by londumas** [comment]
https://github.com/igmhub/pyLyA/pull/78

fixed in fix_issue_77
