### ISSUE TITLE
auto correlation with same wavelength

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#79]
In the auto correlation you keep the correlation between two pixels with exactly the same lambda_obs.
I think I remember that you told me we shouldn't since this is where there is a lot of systematics from the pipeline with object from the same plate
Am I wrong ?
It is here  https://github.com/igmhub/pyLyA/blob/master/py/pylya/cf.py in fast_cf

**Comment by ngbusca** [comment]
They are masked if they are in the same half plate.

**Comment by ngbusca** [comment]
see lines 89 to 92 of cf.py

**Comment by londumas** [comment]
indeed, sory.
