### ISSUE TITLE
cross-correlation calculation misses pairs

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#8]
The calculation of angmax:

xcf.angmax = sp.arcsin(xcf.rt_max/cosmo.r_comoving(constants.boss_lambda_min/args.lambda_abs-1))

should take into account the xcf.rp_min (i.e. most of the time -200 Mpc.h-1) in the calculation.

For now it misses pairs.

**Comment by londumas** [comment]
So it should be:
`
cosmo.r_comoving(constants.boss_lambda_min/args.lambda_abs-1)+xcf.rp_min
`

**Comment by ngbusca** [comment]
Do you want to branch, make the modif and merge request?

**Comment by londumas** [comment]
For now,
I am just putting the issue on gitHub so I don't forget them.
I will take care of correcting them after, I can't now.

**Comment by londumas** [comment]
fixed in fix_issue_8
