### ISSUE TITLE
io.py looks for a missing key in dic is no spectrum

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#83]
The new logic for the pixel is crashing if a spectrum is missing:
The line:
idx = thid2idx[t]
is looking then for an unknown key in a dic

**Comment by ngbusca** [comment]
I'll take a look

**Comment by ngbusca** [comment]
When a thing_id is not found in the pixel file the code will report it in the log file. Can you check if this has been logged correctly?

**Comment by ngbusca** [comment]
Yes, the thing_id in DR12 are different from DR14

**Comment by ngbusca** [comment]
I've added handling to master for when thing ids are not found in the pixel files

**Comment by londumas** [comment]
fixed in bug_in_io
