### ISSUE TITLE
add storing zeff and err_zeff in export.py

### ISSUE THREAD

**Issue by londumas** [igmhub/pyLyA#85]
In export.py we could and should add calculating zeff and its error
and storing them in the header of the output file.

**Comment by ngbusca** [comment]
I'm not sure I agree. The user has zeff per bin and the weight per bin so she can compute it according to her application (e.g., the zeff of bao might be different from the zeff at low separations). Some day we might find that's better to define zeff between 90 and 110 Mpc/h instead of 80 and 120 Mpc/h, we dont' want to rerun export.py to change that.

**Comment by londumas** [comment]
indeed, but we could add a command "argparse" for r_min_for_zeff and r_min_for_zeff set to 80,120 by default. But it complicates the simple export.py.

I don't know exactly what we should do but I don't really like the fact that the output results in pyLya_fitter
are given at the near unphysical zref and not at the really physical zeff (whatever its definition).

We could simply add a zeff parameter in pyLya_fitter and the user gives what ever he want.

**Comment by londumas** [comment]
this is linked to issue https://gitlab.in2p3.fr/ngbusca/pyLyA/issues/110

**Comment by ngbusca** [comment]
Is this a matter of principle? Could you describe the specific problem you are encountering?

**Comment by londumas** [comment]
our measure is at z~zeff not at the zref of the input power spectrum.
Thus we shouldn't give the result in the save.pars and in the papers at zref.

**Comment by londumas** [comment]
even if we can easily convert them.

**Comment by ngbusca** [comment]
This is up to the user. Nothing prevents the user from generating an input at zeff.

**Comment by londumas** [comment]
not totally true, because the user would have to write a code to do the peak sideband decomposition.

But indeed, you are right, when this code will be somewhere in IgmHub (in Python or free to use software) the user will do whatever he wants.

For now we are kind of stuck with using z=2.25 or z=2.40 produced for me by Michael

**Comment by ngbusca** [comment]
That's right. We should ask Michael to make this code available (might be already part of baofit?)

**Comment by londumas** [comment]
the code is currently in mathematica (140€)
here https://github.com/deepzot/mathpkg
